### PR TITLE
Reconvert spsc unbounded atomic array queue

### LINKED ISSUE #165: Port SPSC linked array queues to atomic versions
see #164

### PR DESCRIPTION
**Pull request by neomatrix369**
- rename classes 
- reconvert SPSC unbounded array queue to SPSC unbounded atomic array queue 

Fully fixes #165

### CODE REVIEW

**Comment by nitsanw** [comment]
Thanks Mani! Looking forward to further contributions and collaborations!

**Comment by neomatrix369** [comment]
Thanks for the support and opportunity @nitsanw, looking forward to contributing more to this project

**Comment by neomatrix369** [comment]
@nitsanw what's the next best issue to pick from the list of git issues

**Comment by nitsanw** [comment]
@neomatrix369 how about #178 which is similar work? It would be good to have the atomic package consistent with the queues package for the next release. If you can start with a review to map the territory we can split tasks for particular queues and maybe spread the load. Thanks!

**Pull request merged**
