### PR TITLE
Add integration with Coveralls.io

### PR DESCRIPTION
**Pull request by maseev**
This PR adds integration with Coveralls.io which was discussed [here](https://github.com/JCTools/JCTools/issues/170).

### CODE REVIEW

**Comment by maseev** [comment]
Don't forget that you still need to sign in to Coveralls and add your github repository.

**Comment by nitsanw** [comment]
Does it build ok with Jdk9?

**Comment by maseev** [comment]
I haven't tried. But it seems that you build JCTools only with JDK 8, according to [.travis.yml](https://github.com/JCTools/JCTools/blob/master/.travis.yml#L3). I can try to build it with JDK 9, just to make sure that everything works OK.

**Comment by maseev** [comment]
It looks like it builds just OK with [JDK 9](https://travis-ci.org/maseev/JCTools/builds/303909986). Should I remove JDK 9 from the .travis.yml for now?

**Comment by maseev** [comment]
I think it would be better to separate these two tasks - building JCTools with JDK 8 and 9 and integration with Coveralls.io.

**Comment by maseev** [comment]
It seems that `clean test` in the `after_success` section is really unnecessary. It actually makes tests run twice.

**Comment by maseev** [comment]
@nitsanw PTAL.

**Comment by maseev** [comment]
Is there anything else I can do to get this PR merged?

**Comment by nitsanw** [comment]
Sorry dude, will have a look ASAP, currently swamped

**Comment by nitsanw** [comment]
Thanks for the contribution!

**Pull request merged**
