### PR TITLE
Migration to Java 7, Maven tidied up and code inspections.

### PR DESCRIPTION
**Pull request by guidomedina**
The following has been done:
* Migrated to Java 7.
* Maven dependencies and plugins updated.
* Maven properties created at parent project and most things are now declared at parent project.
* IntelliJ 15.0.3 inspections and corrections applied with no side effect or functionality changed.

### CODE REVIEW

**Comment by guidomedina** [comment]
Maven compiler bug starting at version 3.2 and up, fixing.

**Comment by nitsanw** [comment]
Hi, JCTools core is Java 1.6, tests/experimental/benchmarks are 1.8.

**Comment by guidomedina** [comment]
ok, will redo for Java 6 then, it is much nicer in Java 7 TBH, I don't get why people are stuck in Java 6 when there is basically free to move to Java 7 and gain lots of performance with new concurrent stuff, etc.

**Comment by guidomedina** [comment]
It might be possible to create a new branch for Java 7 though? Some people might prefer the Java 7 version, you can always keep 1.1.x and 1.2.x and then 2.0 for Java 8? what do you think?

**Comment by nitsanw** [comment]
:-) I'll drop Java6 support at some point I guess, but this is a product/lib so we have to accomodate the wider public. IT environments are slow to move and tend to have insane policies around these things made by people with a different decision making process...

**Pull request closed without merging**
