### PR TITLE
Fix replace missing value

### PR DESCRIPTION
**Pull request by fvlad**
Fix to the issue https://github.com/JCTools/JCTools/issues/244 to avoid throwing AssertionError when value is missing by key on replace

### CODE REVIEW

**Comment by nitsanw** [comment]
Javadoc for replace:
"replace(K key, V value): Replaces the entry for the specified key only if it is currently mapped to some value."
So, we expect a null reply, and the assert in putIfMatch seems to contradict the contract.

The code in `putIfMatch` has an assert that is stronger than the guarantees in the static `putIfMatch`, but that assert is valid for all case where the `oldVal` param is not `MATCH_ANY`. I think the right move here is to add this observation to the assert:
```
assert res != null || oldVal == MATCH_ANY;
```

**Comment by nitsanw** [comment]
Further digging after https://github.com/JCTools/JCTools/pull/246#issuecomment-496482459 leads me to think that putIfMatch should have returned TOMBSTONE instead of null here.

**Comment by nitsanw** [comment]
Please see changes in https://github.com/JCTools/JCTools/commit/1475be5e072677ecb657bd80649025a00fdf43bd which resolve the issue. I'm very grateful for the PR and would happily merge it if you revert the change to NBHM. Thanks!

**Comment by fvlad** [comment]
Great, thanks for your fix!

**Pull request closed without merging**
