### PR TITLE
Adding specific support for Xadd benchmarks

### PR DESCRIPTION
**Pull request by franz1981**

### CODE REVIEW

**Comment by nitsanw** [comment]
@geektcp thanks for your interest, it would be good if you became a code contributor before doing reviews though. Why not pick up a couple of issues to work on?

**Comment by nitsanw** [comment]
@franz1981 please re-evaluate the need for this in light of the adjustment made in https://github.com/JCTools/JCTools/commit/2fd35936cc37abe568acdb648c587501a6284db5

**Comment by franz1981** [comment]
@nitsanw Will look at It soon, thanks to pointed it, I have missed it!!

**Comment by franz1981** [comment]
@nitsanw thanks to pointing me the most recent changes on factory: I've modified the benchs just to account for stretching beyong the pooled chunks in the setup phase

**Pull request merged**
